---
version: 2.1

orbs:
  terraform: feedyard/terraform@dev:latest

workflows:
  version: 2

  tf-aws-platform-vpc-module-ci-pipeline:
    jobs:
      - terraform/lint
      - terraform/module-ci:
          context: global
          working_directory: test/fixture
          aws-access-key-id: $FEEDYARD_SANDBOX_CI_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $FEEDYARD_SANDBOC_CI_AWS_SECRET_ACCESS_KEY
          aws-region: us-east-1
          after-terraform:
            - run:
                name: use awspec to validate aws configuration
                environment:
                  PLATFORM_ENV: ci
                  AWS_REGION: us-east-1
                command: rspec ../integration
